# 应用服务 WEB 访问端口
spring:
  application:
    name: user-center



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 解决Spring Boot版本 >= 2.6.x 版本与Swagger2 2.9.2 不兼容问题

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yifan  #  /user_center?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: Dyf981024.

  # redis配置
  redis:
    host: localhost
    port: 6379  # redis默认端口
    database: 0  # redis默认数据库索引为0

  # 配置session失效时间(单位:秒)
  session:
    timeout: 86400
    store-type: redis
server:
  port: 8080
  servlet:
    context-path: /api # 所有请求都添加/api前缀

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志打印
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0






